name: cashbook
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  bootstrap_icons: ^1.11.3
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  google_fonts: 6.1.0
  provider: ^6.0.3
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/add_button/
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/roboto/Roboto-Regular.ttf
  #       - asset: assets/fonts/roboto/Roboto-Italic.ttf
  #         style: italic
  #       - asset: assets/fonts/roboto/Roboto-Bold.ttf
  #         weight: 700
